# Generated by Django 5.2 on 2025-10-17 10:51

import cloudinary.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateField(help_text='Please select a date from today onwards.', validators=[django.core.validators.MinValueValidator(datetime.date.today, message='Event date cannot be in the past.')])),
                ('poster', cloudinary.models.CloudinaryField(blank=True, help_text='Optional: Upload an event poster.', max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
