# Generated by Django 5.2 on 2025-10-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_add_is_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='is_unique',
            field=models.BooleanField(default=False, help_text='If true, single-copy item using status instead of stock.'),
        ),
    ]
