# Generated by Django 5.2 on 2025-10-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], db_index=True, default='pending', max_length=16)),
                ('confirm_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('locale', models.CharField(blank=True, max_length=8)),
                ('consent_text', models.CharField(blank=True, max_length=255)),
                ('consent_source', models.CharField(blank=True, max_length=64)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='newsletter.subscriber')),
            ],
        ),
    ]
