# Generated by Django 5.2 on 2025-10-19 16:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional: Upload a profile picture.', max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
