# Generated by Django 5.2 on 2025-10-19 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdata',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional: Upload a a featured video.', max_length=255, null=True),
        ),
    ]
