# Generated by Django 5.2 on 2025-10-20 07:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutdata_video'),
        ('gallery', '0004_alter_stockitem_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdata',
            name='artist_statement',
            field=models.TextField(blank=True, help_text='Artist statement or creative process description.'),
        ),
        migrations.AddField(
            model_name='aboutdata',
            name='biography',
            field=models.TextField(blank=True, help_text='Artist biography or personal story.'),
        ),
        migrations.AddField(
            model_name='aboutdata',
            name='featured_artworks',
            field=models.ManyToManyField(blank=True, help_text='Select artworks to feature in the about section.', related_name='featured_in_about', to='gallery.painting'),
        ),
        migrations.AddField(
            model_name='aboutdata',
            name='mission_statement',
            field=models.TextField(blank=True, help_text='Mission statement or artistic philosophy.'),
        ),
        migrations.AlterField(
            model_name='aboutdata',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional: Upload a featured video.', max_length=255, null=True),
        ),
    ]
